### ISSUE TITLE
'react-scripts start' fails on MacOS

### ISSUE THREAD

**Issue by wmuece** [marmelab/sketch-by-phone#30]
see log file
[npm-debug.log.txt](https://github.com/marmelab/sketch-by-phone/files/1255021/npm-debug.log.txt)

**Comment by djhi** [comment]
Have you tried removing the `package-lock.json` file ?

**Comment by wmuece** [comment]
Thank you for writing back, Gildas.

No, I did not, and I am not sure why I have to (I am a bit of a newby on node.js things).

If I could ask you for some instruction, that would be very much appreciated.

You have a very innovative AR product!

- Dean

On Aug 28, 2017, at 4:16 PM, Gildas Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you tried removing the package-lock.json file ?

**Comment by djhi** [comment]
Thanks :)
You're the second person saying it doesn't work on osX, for different reasons though.

I see that you're on node 6 and npm 3. Can you try upgrading those ? Maybe using [nvm](https://github.com/creationix/nvm) ?

**Comment by wmuece** [comment]
Gildas:  Ok, I see that I did not install sketch-by-phone in the right order (didn’t go down enough to see the makes).
It seems to be running out of localhost fine now.  Fake issue, I am sorry I posted it.
When iOS11 comes out, I will be ready to cast some image templates to students in the lecture hall for use in iClicker assignments!
- Dean

On Aug 28, 2017, at 4:42 PM, Gildas Garcia <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks :)
You're the second person saying it doesn't work on osX, for different reasons though.

I see that you're on node 6 and npm 3. Can you try upgrading those ? Maybe using nvm<https://github.com/creationix/nvm> ?

**Comment by djhi** [comment]
No problem :)

**Comment by wmuece** [comment]
Hello Gildas

I did not get sketch-by phone to turn on camera on my iPhone6 properly with iOS 6.  (Etennie's ar.js demo display great however.  Any ideas?

[image1.png]

Sent from my iPhone ... Dean

**Comment by fzaninotto** [comment]
sketch-by-phone doesn't work on iOS, that's a known limitation.

**Comment by wmuece** [comment]
Francois:
We updated the ar.js and three.js libraries and sketch-by-phone NOW WORKS on iOS (Safari only, Chrome has usual WebRTC problem).
Behaves same as on Android, showing some skewing of images — but on MacOS no skewing shows.
We are redeveloping it as an AR aid in the lecture hall, as previously stated.
Thank you very much for the great tutorial. - Dean


On Sep 29, 2017, at 5:22 AM, Francois Zaninotto <notifications@github.com<mailto:notifications@github.com>> wrote:


sketch-by-phone doesn't work on iOS, that's a known limitation.
